### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/gsm8k_nl/train_shuf.jsonl'

### ISSUE THREAD

**Issue by ClarkFu007** [yunx-z/SCORE#1]
Dear authors,

I am very interested in your paper and want to run your codes! However, I face one issue for now...

When I am running "python3 sample_ans.py --task gsm8k_nl --model meta-llama/Llama-2-13b-chat-hf --split train --num_generations 10", the screen shows "FileNotFoundError: [Errno 2] No such file or directory: 'data/gsm8k_nl/train_shuf.jsonl'". I failed to get any instructions to prepare the "train_shuf.jsonl" based on your instruction. 

I would be really grateful if you could help me solve this issue. Thank you!

**Comment by yunx-z** [comment]
Hi,

Thank you for your interest in our paper. Sorry for the missing data. I just added [the file you mentioned](https://github.com/yunx-z/SCORE/blob/main/data/gsm8k_nl/train_shuf.jsonl). Please let me know if you have any other questions.
